[tool.poetry]
name = "anki_deck_from_text"
version = "0.1.0"
description = "Generate Anki decks and cards from annotations on a text file"
authors = ["AndreMacedo88 <andre.lopes.macedo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
genanki = "^0.13.1"
click = "^8.1.7"


[tool.poetry.group.dev.dependencies]
nox = "^2023.4.22"
nox-poetry = "^1.0.3"
autopep8 = "^2.0.4"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
